name: Upload

on:
  push:
    branches:
      - "main"

jobs:
  charmhub-upload:
    runs-on: ubuntu-22.04
    name: Charmhub upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: canonical/charming-actions/upload-charm@2.2.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "edge"
